config/routes.rb
ServulaApi::Application.routes.draw do
  resources :endpoints

  root to: 'endpoints#index'

  

end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base

  validates_presence_of :name, :path, :method

  validates_length_of :name, :within => 3..20

  validates_inclusion_of :method, in: %w( get post put delete ), message: "method %s is not a valid method"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /endpoints
  def index
    @endpoints = Endpoint.all
  end

  # GET /endpoints/1
  def show
  end

  # GET /endpoints/new
  def new
    @endpoint = Endpoint.new
  end

  # GET /endpoints/1/edit
  def edit
  end

  # POST /endpoints
  def create
    @endpoint = Endpoint.new(endpoint_params)

    if @endpoint.save
      redirect_to @endpoint, notice: 'Endpoint was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /endpoints/1
  def update
    if @endpoint.update(endpoint_params)
      redirect_to @endpoint, notice: 'Endpoint was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /endpoints/1
  def destroy
    @endpoint.destroy
    redirect_to endpoints_url, notice: 'Endpoint was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endpoint
      @endpoint = Endpoint.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def endpoint_params
      params.require(:endpoint).permit(:name, :path, :method, :description, :parameters, :example)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
  def method_options_for_select(selected = nil)
    methods = %w( get post put delete )
    options_for_select(methods, selected)
  end
end

app/views/endpoints/_form.html.haml
= form_for @endpoint do |f|
  - if @endpoint.errors.any?
    #error_explanation
      %h2= "#{pluralize(@endpoint.errors.count, "error")} prohibited this endpoint from being saved:"
      %ul
        - @endpoint.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :path
    = f.text_field :path
  .field
    = f.label :method
    = f.select :method, method_options_for_select(f.object.method)
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :parameters
    = f.text_area :parameters
  .field
    = f.label :example
    = f.text_area :example
  .actions
    = f.submit 'Save', class: 'button small radius'

app/views/endpoints/edit.html.haml
%h1 Editing endpoint

= render 'form'

= link_to 'Show', @endpoint
\|
= link_to 'Back', endpoints_path

app/views/endpoints/index.html.haml
%h1 Listing endpoints

%ul
  - @endpoints.each do |endpoint|
    %li
      %h3= endpoint.name
      %p= endpoint.description
      = link_to 'Show', endpoint

-#      
  %table
    %tr
      %th Name
      %th Path
      %th Method
      %th Description
      %th Parameters
      %th Example
      %th
      %th
      %th

    - @endpoints.each do |endpoint|
      %tr
        %td= endpoint.name
        %td= endpoint.path
        %td= endpoint.method
        %td= endpoint.description
        %td= endpoint.parameters
        %td= endpoint.example
        %td= link_to 'Show', endpoint
        %td= link_to 'Edit', edit_endpoint_path(endpoint)
        %td= link_to 'Destroy', endpoint, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

= link_to 'New Endpoint', new_endpoint_path

app/views/endpoints/new.html.haml
%h1 New endpoint

= render 'form'

= link_to 'Back', endpoints_path

app/views/endpoints/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @endpoint.name
%p
  %b Path:
  = @endpoint.path
%p
  %b Method:
  = @endpoint.method
%p
  %b Description:
  = @endpoint.description
%p
  %b Parameters:
  = @endpoint.parameters
%p
  %b Example:
  = @endpoint.example

= link_to 'Edit', edit_endpoint_path(@endpoint)
\|
= link_to 'Back', endpoints_path

app/views/layouts/_sidebar.html.haml
- if Endpoint.any?
  %h3 Endpoints
  %ul.side-nav
    - Endpoint.all.each do |endpoint|
      %li
        = link_to endpoint.name, endpoint

= link_to 'Servula', 'https://my.servula.com'

app/views/layouts/application.html.haml
!!! 5

/[if lt IE 7]
  %html{class: 'ie6', lang: 'en'}
/[if IE 7]
  %html{class: 'ie7', lang: 'en'}
/[if IE 8]
  %html{class: 'ie8', lang: 'en'}
/[if (gte IE 9)|!(IE)]
  :plain
    <!--><html lang="en"> <!--

%head
  %meta{charset: 'utf-8'}
  %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
  %title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Kelly+Slab|Gudea'
  = stylesheet_link_tag 'application'
  =# javascript_include_tag 'vendor/custom.modernizr'
  = csrf_meta_tags

%body
  %header.row
    %h1
      = link_to image_tag('https://my.servula.com/assets/header/logo-beta.png'), root_url
      = link_to 'dev.servula.com', root_url

  .row#main
    %aside.columns.small-3
      = render 'layouts/sidebar'
    .columns.small-9
      = yield


  %footer.row
    .columns.small-12
      &copy; Servula

  = javascript_include_tag "application"